### ISSUE TITLE
After move functions to LiveComponent, LiveView count does not re-render.

### ISSUE THREAD

**Issue by GrassHopper42** [dwyl/phoenix-liveview-todo-list-tutorial#93]
I'm about to finish this tutorial and create my own, but I realized that the to-do count doesn't re-render when the item status is changed - not just mine, but yours as well. If I want to change count whenever status updated, What can I do?

**Comment by SimonLab** [comment]
Thanks for spotting this bug @GrassHopper42 
Indeed the count is not updated for the client. However if another client is open it is.
![image](https://user-images.githubusercontent.com/6057298/218729907-a1f5ec32-bf89-429a-8eb8-88ce167af709.png)
(3 items left but all checked)

This is due to the `broadcast_from` function not sending the event of the item being updated to the client who triggered the event.
https://github.com/dwyl/phoenix-liveview-todo-list-tutorial/blob/eb392e2e4ca644c90e73a0e9905414c0e0c36373/lib/live_view_todo_web/live/item_component.ex#L70

One solution is to use [broadcast](https://hexdocs.pm/phoenix/Phoenix.Endpoint.html#c:broadcast/3) instead of `broadcast_from`

**Comment by GrassHopper42** [comment]
Cool!!! It works! Thank you sooooooo much.
I love your tutorials.

**Comment by nelsonic** [comment]
@GrassHopper42 thanks very much for reporting this issue. Glad you're finding the tutorials useful. ❤️ 
@SimonLab thanks for the quick fix/turnaround. :shipit:
